trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - infra

pool:
  vmImage: ubuntu-latest

variables:

- name: deploymentDefaultLocation
  value: centralus
- name: ResourceGroupName
  value: DevGroup


jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: infra/main.bicep
      csmParametersFile: infra/dev.param.json
