trigger: none

pool:
  vmImage: ubuntu-latest

variables:

- name: deploymentDefaultLocation
  value: centralus
- name: ResourceGroupName
  value: DevGroup


jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: main.bicep
      overrideParameters: >
        -environmentType $(EnvironmentType)
        -deployToyManualsStorageAccount $(DeployToyManualsStorageAccount)