trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:

- name: deploymentDefaultLocation
  value: centralus
- name: ResourceGroupName
  value: DevGroup
- name: ServiceConnectionName
  value: dev-connection


jobs:
- job:
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: "Resource Group"
      connectedServiceName: $(ServiceConnectionName)
      deploymentName: $(Build.BuildNumber)
      location: $(deploymentDefaultLocation)
      resourceGroupName: $(ResourceGroupName)
      csmFile: main.bicep
      csmParametersFile: dev.param.json
